### ISSUE TITLE
compiler complains about source level (and then when fixed) generics

### ISSUE THREAD

**Issue by alphazero** [jfager/functional-critbit#1]
First off, running mvn against the vanilla pull of the repo raises errors due to the fact that the pom does not specify source level. So that was addressed (e.g. http://maven.apache.org/general.html#Compiling-J2SE-5)

That done, here is the mvn compile out:

`[INFO] Compilation failure
/Users/alphazero/Code/oss/github/jfager/functional-critbit/src/main/java/io/prelink/critbit/AbstractCritBitTree.java:[306,17] type parameters of <T>T cannot be determined; no unique maximal instance exists for type variable T with upper bounds K,java.lang.Object`

**Comment by jfager** [comment]
Ah, okay.  Which version of javac are you using?  

That use of cast() snuck in when I added java.util.Map interface compliance in September.  The jdk release that fixed the [issue](http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6302954) that caused this usage to fail in javac was 1.6.0_25, which I had updated past by the time I was working on this. 

I've eliminated all naked cast calls, and updated the pom.  I don't have an older version of javac available atm to check it, so if you could please let me know if head now works for you, I'd appreciate it.

Thanks for the report.

**Comment by alphazero** [comment]
Great, will check it.  FYI it is javac 1.6.0_17 on Mac OS X 10.6.

**Comment by alphazero** [comment]
Sorry for delay in getting back.  Just pulled and tested with javac 1.6.0_17 and all is OK.

Thank you!

**Comment by jfager** [comment]
Great to hear, thanks again.
